# Generated by Django 4.2.2 on 2023-07-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=15, max_digits=20)),
                ("longitude", models.DecimalField(decimal_places=15, max_digits=20)),
                ("cluster", models.IntegerField()),
            ],
        ),
    ]
